#!/usr/bin/env node
/**
 * gen-assets.mjs — inline the vendored report assets into a TypeScript module.
 *
 * `hop report --html` emits a single self-contained file, so the CSS and JS have
 * to travel inside the CLI bundle rather than being read from disk at runtime.
 * The installed runtime lives at ~/.hop/bin/hop-cli.js with no sibling asset
 * directory, so a runtime read would break exactly the way `hop validate`'s
 * schema lookup does.
 *
 * Run after re-vendoring assets/:  bun run gen-assets
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const assetDir = join(repoRoot, "packages", "hop-cli", "assets");
const outFile = join(repoRoot, "packages", "hop-cli", "src", "assets.generated.ts");

/** Escape a file's contents for embedding in a TS template literal. */
function toTemplateLiteral(text) {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

const css = readFileSync(join(assetDir, "foundation.css"), "utf-8");
const js = readFileSync(join(assetDir, "foundation.js"), "utf-8");

// `</script>` inside a JS string would close the host <script> element early.
const safeJs = js.replace(/<\/script>/gi, "<\\/script>");

const banner = `/**
 * AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.
 *
 * Inlines packages/hop-cli/assets/foundation.{css,js} so \`hop report --html\`
 * can emit a single self-contained file. To update: replace the files in
 * assets/ and run \`bun run gen-assets\`.
 */
`;

const body = `${banner}
export const FOUNDATION_CSS = \`${toTemplateLiteral(css)}\`;

export const FOUNDATION_JS = \`${toTemplateLiteral(safeJs)}\`;
`;

writeFileSync(outFile, body, "utf-8");
console.log(
  `Wrote ${outFile}\n  foundation.css  ${css.length} bytes\n  foundation.js   ${js.length} bytes`
);
